name: CI/CD Pipeline for Flask

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH Key
      run: |
        echo "$KEY" > deploy_key.pem
        chmod 600 deploy_key.pem

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no -i deploy_key.pem $USER@$HOST << EOF
          echo "Pulling latest code..."
          cd /home/ubuntu/DevOpsSec_Flask-Project
          git pull origin main
          echo "Activating virtual environment and installing dependencies..."
          source venv/bin/activate
          pip install -r requirements.txt
          echo "Restarting application..."
          sudo systemctl restart myflaskapp
          echo "Deployment completed!"
        EOF
