name: CI/CD for EC2 Deployment

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Debug SSH Key
      run: |
        echo "$KEY" > deploy_key.pem
        chmod 600 deploy_key.pem
        ls -l deploy_key.pem  # Check if the file exists
        cat deploy_key.pem | head -n 5  # Verify the first 5 lines of the key

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no -i deploy_key.pem $USER@$HOST << EOF
          echo "Pulling latest code..."
          cd /home/ubuntu/DevOpsSec_Flask-Project
          git pull origin main
          echo "Activating virtual environment..."
          source venv/bin/activate
          pip install -r requirements.txt
          echo "Restarting application..."
          sudo systemctl restart myapp.service
          echo "Deployment completed!"
        EOF
